nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/': # Replace this with your Symfony app's API endpoints path
            allow_origin: ['*'] # Replace this with your Nuxt app's URL
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
            max_age: 3600
