version: '3.8'

services:
    app:
        container_name: inbenta-test
        build:
            context: ./.docker
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
