version: '3.8'

services:
    app:
        container_name: inbenta-test
        build:
            context: ./.docker
            dockerfile: Dockerfile
        tty: true
        ports:
            - "8080:80"
            - "4430:443"
        volumes:
            - .:/var/www/html
        networks:
            - inbenta-test-network
networks:
    inbenta-test-network:
        driver: bridge